schema_version = "1.0.0"

id = "d_replicator"
version = "1.0.0"
name = "D_Replicator"
tagline = "Non-destructive mass-cloning & animation toolkit"
maintainer = "Signal88."
type = "add-on"

website = "https://sgnl88.com/"

tags = ["Object", "Modeling", "Animation"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 Signal88.",
]
